library (ggplot2)
library(e1071)
DATA=read.csv(file.choose(),sep=',',header=T)
str(DATA)
DATA$admit=as.factor(DATA$admit)
DATA$rank=as.factor(DATA$rank)
DATA$gre=(DATA$gre-min(DATA$gre))/(max(DATA$gre)-min(DATA$gre))
DATA$gpa=(DATA$gpa-min(DATA$gpa))/(max(DATA$gpa)-min(DATA$gpa))
set.seed(124)
qplot(DATA$gre,DATA$gpa,data=DATA,color=DATA$admit)
SVMMODELENT=svm(admit~.,data=DATA)
summary(SVMMODELENT)
SVMPREDICTIONENT=predict(SVMMODELENT,DATA)
(Tab=table(SVMPREDICTIONENT,DATA$admit))

(SVMPERFORMANCE=sum(diag(Tab))/sum(Tab)*100)
SVMPREDICTION=predict(SVMMODEL,IRIS)
TUNEDSVMMODELENT=tune(svm,admit~.,data=DATA,ranges=list(epsilon=seq(0.1,0.1),cost=2^(2:9)))
TUNEDSVMMODELENT$best.model
summary(TUNEDSVMMODELENT)
